# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

# The minimum number of reviews from each association that approve the pull request before
# doing an automatic merge. For more information about associations see:
# https://developer.github.com/v4/enum/commentauthorassociation/
minApprovals:
  MEMBER: 1
  COLLABORATOR: 2

# Pull requests will only be automatically merged when all of these reviewers have approved the
# pull request.
requiredReviewers:
- xinbenlv

