# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

# Pull requests will only be automatically merged when all of these reviewers have approved the
# pull request.
requiredReviewers:
- xinbenlv

